import {boot} from "../shared/bootstrap.js"; import {getData,objectiveProgress} from "../data/store.js"; import {progressHTML,statusLabel,fmtDate} from "../shared/utils.js";
if(boot("admin","dashboard")) render();
function render(){const d=getData(),tasks=d.tasks.filter(t=>t.status!=="cancelled"),done=tasks.filter(t=>t.progress>=100).length,inprog=tasks.filter(t=>t.progress>0&&t.progress<100).length,notStarted=tasks.filter(t=>t.progress===0).length,overdue=tasks.filter(t=>t.date<"2026-10-06"&&t.progress<100).length,avg=tasks.length?Math.round(tasks.reduce((a,t)=>a+t.progress,0)/tasks.length):0;
const byWorker=d.workers.map(w=>{const ts=tasks.filter(t=>t.workerIds.includes(w.id));return {name:w.name.split(" ")[0],value:ts.length?Math.round(ts.reduce((a,t)=>a+t.progress,0)/ts.length):0}});
const total=Math.max(1,tasks.length),donePct=Math.round(done/total*100),progPct=Math.round(inprog/total*100);
document.querySelector("#pageContent").innerHTML=`
<div class="grid stats-grid"><div class="card stat"><div class="stat-label">ACTIVE WORKERS</div><div class="stat-value">${d.workers.filter(w=>w.active).length}</div><div class="stat-foot">${d.attendance.filter(a=>a.date==="2026-10-06"&&a.status==="present").length} present today</div></div><div class="card stat"><div class="stat-label">OPEN TASKS</div><div class="stat-value">${tasks.length-done}</div><div class="stat-foot">${done} completed</div></div><div class="card stat"><div class="stat-label">OVERDUE</div><div class="stat-value">${overdue}</div><div class="stat-foot">Needs attention</div></div><div class="card stat"><div class="stat-label">GLOBAL PROGRESS</div><div class="stat-value">${avg}%</div><div class="stat-foot">Across active tasks</div></div></div>
<div class="grid two-col"><section class="card"><div class="section-head"><h2>Worker performance</h2><span class="badge progress">Average task progress</span></div><div class="chart-bars">${byWorker.map(x=>`<div class="chart-bar-wrap"><div class="chart-value">${x.value}%</div><div class="chart-bar" style="height:${Math.max(5,x.value)}%"></div><div class="chart-label">${x.name}</div></div>`).join("")}</div></section><section class="card"><div class="section-head"><h2>Task distribution</h2><span class="badge">${tasks.length} tasks</span></div><div class="donut-wrap"><div class="donut" style="--done:${donePct}%;--progress:${donePct+progPct}%"><div class="donut-center">${donePct}% done</div></div><div class="legend"><div class="legend-row"><span class="legend-dot"></span>Completed · ${done}</div><div class="legend-row"><span class="legend-dot blue"></span>In progress · ${inprog}</div><div class="legend-row"><span class="legend-dot muted-dot"></span>Not started · ${notStarted}</div></div></div></section></div>
<div class="grid two-col" style="margin-top:16px"><section class="card"><div class="section-head"><h2>Objective health</h2></div>${d.objectives.map(o=>{const p=objectiveProgress(o,d);return `<div style="margin-bottom:18px"><div class="metric-line"><strong>${o.title}</strong><span>${p}%</span></div>${progressHTML(p)}<div class="small muted" style="margin-top:6px">Due ${fmtDate(o.due)}</div></div>`}).join("")}</section><section class="card"><div class="section-head"><h2>Leaderboard</h2><a class="small muted" href="workers.html">View workers</a></div><div class="list">${[...d.workers].sort((a,b)=>b.points-a.points).map((w,i)=>`<div class="list-row"><div><span class="badge">#${i+1}</span> <strong>${w.name}</strong></div><span>${w.job}</span><span>${w.points} pts</span><a class="btn ghost small" href="worker-details.html?id=${w.id}">Open</a></div>`).join("")}</div></section></div>
<section class="card" style="margin-top:16px"><div class="section-head"><h2>Today's activity</h2></div><div class="activity">${tasks.slice(0,6).map(t=>`<div class="activity-item"><strong>${t.title}</strong><div class="small muted">${statusLabel(t.status)} · ${t.progress}% · ${t.deadline}</div></div>`).join("")}</div></section>`}
