import {boot} from "../shared/bootstrap.js"; import {getData,updateData} from "../data/store.js"; import {modal,toast,esc} from "../shared/utils.js"; import {supabase} from "../config/supabase.js";
let selected=new Set(); if(boot("admin","workers")) render();
function render(){const d=getData();document.querySelector("#pageActions").innerHTML=`<button class="btn primary" id="addWorker">+ Add worker</button>`;document.querySelector("#pageContent").innerHTML=`<section class="card"><div id="selection"></div><div class="toolbar"><input id="search" placeholder="Search workers..."><span class="spacer"></span><span class="small muted">${d.workers.length} records</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th class="select-cell"><input class="select-all" type="checkbox"></th><th>Worker</th><th>ID</th><th>Job</th><th>Salary</th><th>Points</th><th>Status</th><th>Actions</th></tr></thead><tbody id="rows">${rows(d.workers)}</tbody></table></div></section>`;bind(d)}
function rows(ws){return ws.map(w=>`<tr><td><input class="row-check" type="checkbox" data-select="${w.id}" ${selected.has(w.id)?"checked":""}></td><td class="clickable" data-open="${w.id}"><strong>${esc(w.name)}</strong><br><small class="muted">${esc(w.phone)}</small></td><td>${w.code}</td><td>${esc(w.job)}</td><td>${w.salary} TND</td><td>${w.points}</td><td><span class="badge ${w.active?"done":"overdue"}">${w.active?"Active":"Disabled"}</span></td><td><div class="action-group"><button class="btn ghost compact" data-edit="${w.id}">Edit</button><button class="btn danger compact" data-delete="${w.id}">Remove</button></div></td></tr>`).join("")}
function bind(d){document.querySelector("#addWorker").onclick=()=>workerModal();document.querySelector("#search").oninput=e=>document.querySelector("#rows").innerHTML=rows(d.workers.filter(w=>w.name.toLowerCase().includes(e.target.value.toLowerCase())||w.code.includes(e.target.value.toUpperCase())));document.querySelector(".select-all").onchange=e=>{selected=e.target.checked?new Set(d.workers.map(w=>w.id)):new Set();render()};updateSelection();}
function updateSelection(){const box=document.querySelector("#selection");if(box)box.innerHTML=selected.size?`<div class="selection-bar"><strong>${selected.size} selected</strong><button class="btn danger compact" id="removeSelected">Remove selected</button></div>`:"";const b=document.querySelector("#removeSelected");if(b)b.onclick=()=>removeMany([...selected])}
document.addEventListener("click",e=>{const c=e.target.closest("[data-select]");if(c)return;const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]"),open=e.target.closest("[data-open]");if(edit)workerModal(edit.dataset.edit);else if(del)removeMany([del.dataset.delete]);else if(open)location.href=`worker-details.html?id=${open.dataset.open}`});document.addEventListener("change",e=>{if(e.target.matches("[data-select]")){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);updateSelection()}});
function workerModal(id){
 const d=getData(),w=d.workers.find(x=>x.id===id);
 modal(w?"Edit worker":"Add worker",`<div class="form-grid"><label>Name<input name="name" value="${esc(w?.name||"")}" required></label><label>Worker ID<input name="code" value="${w?.code||`WRK${String(d.workers.length+1).padStart(3,"0")}`}" required></label>${w?"":`<label>Passcode<input name="passcode" type="password" minlength="6" autocomplete="new-password" required></label>`}<label>Job / position<input name="job" value="${esc(w?.job||"Farm Worker")}"></label><label>Phone<input name="phone" value="${esc(w?.phone||"")}"></label><label>Salary (TND)<input name="salary" type="number" min="0" value="${w?.salary||0}"></label><label>Hired date<input name="hired" type="date" value="${w?.hired||""}"></label><label>National ID<input name="nationalId" value="${esc(w?.nationalId||"")}"></label><label class="full">Notes<textarea name="notes" rows="3">${esc(w?.notes||"")}</textarea></label></div>`,async fd=>{
   if(w){
     updateData(x=>{const q=x.workers.find(z=>z.id===id);if(q)Object.assign(q,{code:String(fd.get("code")).toUpperCase(),name:fd.get("name"),phone:fd.get("phone"),job:fd.get("job"),salary:Number(fd.get("salary")||0),hired:fd.get("hired"),nationalId:fd.get("nationalId"),notes:fd.get("notes")})});
     toast("Worker updated locally — Supabase edit sync comes next"); render(); return;
   }
   const payload={worker_code:String(fd.get("code")).trim().toUpperCase(),full_name:String(fd.get("name")).trim(),passcode:String(fd.get("passcode")),phone:String(fd.get("phone")||""),job_title:String(fd.get("job")||""),salary:Number(fd.get("salary")||0),hired_date:String(fd.get("hired")||"")||undefined,national_id:String(fd.get("nationalId")||""),notes:String(fd.get("notes")||"")};
   toast("Creating worker…");
   const {data,error}=await supabase.functions.invoke("create-worker",{body:payload});
   if(error||!data?.success){console.error("create-worker failed",error,data);toast(data?.error||error?.message||"Could not create worker","error");return}
   updateData(x=>{x.workers.push({id:data.worker.id,code:data.worker.worker_code,name:data.worker.full_name,photo:"",phone:payload.phone,job:payload.job_title||"Farm Worker",salary:payload.salary,hired:payload.hired_date||"",nationalId:payload.national_id,notes:payload.notes,active:true,points:0})});
   toast(`${data.worker.worker_code} created in Supabase`); render();
 })
}
function removeMany(ids){if(!confirm(`Remove ${ids.length} worker record(s)? Assigned tasks will keep their historical data.`))return;updateData(d=>{d.workers=d.workers.filter(w=>!ids.includes(w.id));d.accounts=d.accounts.filter(a=>!ids.includes(a.workerId));d.attendance=d.attendance.filter(a=>!ids.includes(a.workerId));d.tasks.forEach(t=>t.workerIds=t.workerIds.filter(id=>!ids.includes(id)))});selected.clear();toast("Worker record(s) removed");render()}
